FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.26-openshift-5.1 AS builder
WORKDIR /go/src/github.com/openshift/cluster-machine-approver
COPY . .
RUN make build && gzip -n bin/cluster-machine-approver-tests-ext

FROM registry.ci.openshift.org/ocp/5.1:base-rhel9
COPY --from=builder /go/src/github.com/openshift/cluster-machine-approver/machine-approver /usr/bin/
COPY --from=builder /go/src/github.com/openshift/cluster-machine-approver/bin/cluster-machine-approver-tests-ext.gz /usr/bin/cluster-machine-approver-tests-ext.gz
COPY manifests /manifests
ENTRYPOINT ["/usr/bin/machine-approver"]
LABEL io.k8s.display-name="OpenShift cluster-machine-approver" \
      io.k8s.description="This is an OpenShift component for approving new machines" \
      com.redhat.component="cluster-machine-approver" \
      maintainer="OpenShift Auth Team <aos-auth-team@redhat.com>" \
      name="openshift/ose-cluster-machine-approver" \
      version="v4.0.0" \
      io.openshift.tags="openshift" \
      io.openshift.release.operator=true
